### ISSUE TITLE
Post new videos

### ISSUE THREAD

**Issue by humet** [szdc/tiktok-api#77] opened 2019-01-04 10:49 UTC
**Is your feature request related to a problem? Please describe.**
There currently isn't the ability to post new videos/content.

**Describe the solution you'd like**
An API call we can use to post new videos/content.

**Comment by ducpt2** [comment] 2019-01-04 10:53
Same question :)

**Comment by szdc** [comment] 2019-01-05 00:18
Closing as this is a duplicate of #57.

**Closed by szdc** 2019-01-05 00:18 UTC
