### ISSUE TITLE
follow returns successful but does not follow user

### ISSUE THREAD

**Issue by scrapewww** [szdc/tiktok-api#32] opened 2018-09-19 15:20 UTC
using api, i get a successful response however follow isn't actually created. I can confirm that while using MeMu emulator upon clicking follow button it says following however viewing that users profile i still see follow button. On my profile follower count increases yet user is not within follower list. tiktok must be recognizing something from both api code and emulator and stopping follow action behind the scenes.

**Comment by szdc** [comment] 2018-10-07 13:37
Are you still encountering this?

**Comment by scrapewww** [comment] 2018-10-11 14:19
No - well with your current wrapper than yes. I updated the TikTok app on the emulator, by doing so following became successful. I used Charles to compare the data being sent between the old version and new version, by adding a few variables to the request the following flow is successful. I will compare our files and share the changes I made to fix.

**Comment by szdc** [comment] 2018-10-14 09:02
I'm not seeing any issues running this on my end - the user is followed successfully and can be seen in the followers list.

**Comment by szdc** [comment] 2018-11-01 11:50
Closing as unable to reproduce.

**Closed by szdc** 2018-11-01 11:50 UTC
Labels: question

**Comment by shipsource** [comment] 2020-05-11 13:01
@szdc I think this might be related to the issue I just opened - it's related to a watch_status in response. The value needs to be `1` for a successful follow. Do you know what might be causing the value to be `0`?
