### ISSUE TITLE
device_id

### ISSUE THREAD

**Issue by asosyetikbiri** [szdc/tiktok-api#39] opened 2018-10-23 01:43 UTC
hello device_id how do I create it?

**Comment by scrapewww** [comment] 2018-12-02 18:48
use an app like Charles to watch network requests, grab your own device_id from one of the API calls.

**Comment by asosyetikbiri** [comment] 2018-12-07 21:54
i need to generate my useless device ID

**Comment by szdc** [comment] 2018-12-10 12:10
Closing as this is now a duplicate of the more descriptive issue #58.

**Closed by szdc** 2018-12-10 12:10 UTC
