### ISSUE TITLE
i Have a issue that if i try to login then error code 1105 is occur anyone help me to make login system for tiktok

### ISSUE THREAD

**Issue by umeshdepale** [szdc/tiktok-api#98] opened 2019-04-27 11:47 UTC

**Comment by szdc** [comment] 2019-04-27 11:51
Duplicate of #97.

**Closed by szdc** 2019-04-27 11:51 UTC

**Comment by umeshdepale** [comment] 2019-04-27 11:55
but how to solve This can you please make login system in tiktok for me I can pay some money for this if interested email - vumesh797@gmail.com
